<?php

return [
    'Login' => 'Login',
    'Email Address' => 'Email Id',
    'E-Mail Address' => 'Email Address',
    'Password' => 'Password',
    'Confirm Password' => 'Confirm Password',
    'Remember Me' => 'Remember Me',
    'Forgot Your Password?' => 'Forgot Your Password?',
    'Register' => 'Register',
    'Name' => 'Name',
    'Verify Your Email Address' => 'Verify Your Email Address',
    'A fresh verification link has been sent to your email address.' => 'A fresh verification link has been sent to your email address.',
    'welcome_back' => 'Welcome back! Please sign in to continue',
    'dont_have_account' => 'Don\'t have an account?',
    'register_here' => 'Register here',
    'already_have_account' => 'Already have an account?',
    'login_here' => 'Login here',
    'enter_password' => 'Enter your password',
    'your_email' => 'your@email.com',
    'your_full_name' => 'Your full name',
    'choose_password' => 'Choose a strong password',
    'confirm_password' => 'Confirm your password',
    'one_last_step' => 'One last step to secure your account',
    'before_proceeding' => 'Before proceeding, please check your email for a verification link.',
    'if_not_received' => 'If you did not receive the email',
    'request_another' => 'click here to request another',
    'create_new_password' => 'Create a new password for your account',
    'enter_new_password' => 'Enter new password',
    'confirm_new_password' => 'Confirm new password',
    'remember_password' => 'Remember your password?',
    'enter_email_reset' => 'Enter your email to receive a reset link',
];
