<?php

return [
    'links' => 'Links',
    'dashboard' => 'Admin',
    'profile' => 'Profile',
    'logout' => 'Logout',
    'login' => 'Login',
    'register' => 'Register',
    'support' => 'Support',
    'contact_us' => 'Contact Us',
    'tnc' => 'Terms and Conditions',
    'follow_us' => 'Follow Us',
    'select_language' => 'Select Language',
    'resources' => 'Resources',
    'get_in_touch' => 'Get in touch',
    'documentation' => 'Documentation',
    'components' => 'Components',
    'theme_setup' => 'Theme Setup',
    'connect' => 'Connect',
    'all_rights_reserved' => 'All rights reserved',
    'powered_by' => 'Powered by',
    'privacy_policy' => 'Privacy Policy',
    'terms_of_service' => 'Terms of Service',
    'processed_in' => 'Processed in',
    'config_loader' => 'ConfigLoader',
    'data_loader' => 'DataLoader',
    'page_render' => 'PageRender',
    'copyright' => 'Copyright',
];
