<?php
 
return [
    'Login' => 'लॉगिन',
    'Email Address' => 'ईमेल आईडी',
    'E-Mail Address' => 'ईमेल पता',
    'Password' => 'पासवर्ड',
    'Confirm Password' => 'पासवर्ड की पुष्टि करें',
    'Remember Me' => 'मुझे याद रखें',
    'Forgot Your Password?' => 'अपना पासवर्ड भूल गए?',
    'Register' => 'रजिस्टर',
    'Name' => 'नाम',
    'Verify Your Email Address' => 'अपना ईमेल पता सत्यापित करें',
    'A fresh verification link has been sent to your email address.' => 'आपके ईमेल पते पर एक नया सत्यापन लिंक भेजा गया है।',
    'welcome_back' => 'वापसी पर स्वागत है! कृपया जारी रखने के लिए साइन इन करें',
    'dont_have_account' => 'खाता नहीं है?',
    'register_here' => 'यहाँ रजिस्टर करें',
    'already_have_account' => 'क्या आपके पास पहले से एक खाता है?',
    'login_here' => 'यहाँ लॉगिन करें',
    'enter_password' => 'अपना पासवर्ड दर्ज करें',
    'your_email' => 'your@email.com',
    'your_full_name' => 'आपका पूरा नाम',
    'choose_password' => 'एक मजबूत पासवर्ड चुनें',
    'confirm_password' => 'अपने पासवर्ड की पुष्टि करें',
    'one_last_step' => 'अपने खाते को सुरक्षित करने के लिए एक अंतिम चरण',
    'before_proceeding' => 'आगे बढ़ने से पहले, कृपया सत्यापन लिंक के लिए अपना ईमेल जांचें।',
    'if_not_received' => 'यदि आपको ईमेल प्राप्त नहीं हुआ है',
    'request_another' => 'दूसरे के लिए अनुरोध करने हेतु यहाँ क्लिक करें',
    'create_new_password' => 'अपने खाते के लिए एक नया पासवर्ड बनाएं',
    'enter_new_password' => 'नया पासवर्ड दर्ज करें',
    'confirm_new_password' => 'नए पासवर्ड की पुष्टि करें',
    'remember_password' => 'अपना पासवर्ड याद है?',
    'enter_email_reset' => 'रीसेट लिंक प्राप्त करने के लिए अपना ईमेल दर्ज करें',
];
