<?php
 
return [
    'links' => 'लिंक्स',
    'dashboard' => 'एडमिन',
    'profile' => 'प्रोफ़ाइल',
    'logout' => 'लॉगआउट',
    'login' => 'लॉगिन',
    'register' => 'रजिस्टर',
    'support' => 'सहायता',
    'contact_us' => 'हमसे संपर्क करें',
    'tnc' => 'नियम एवं शर्तें',
    'follow_us' => 'हमें फॉलो करें',
    'select_language' => 'भाषा चुनें',
    'resources' => 'संसाधन',
    'get_in_touch' => 'संपर्क करें',
    'documentation' => 'दस्तावेज़',
    'components' => 'अवयव',
    'theme_setup' => 'थीम सेटअप',
    'connect' => 'जुड़ें',
    'all_rights_reserved' => 'सर्वाधिकार सुरक्षित',
    'powered_by' => 'संचालित द्वारा',
    'privacy_policy' => 'गोपनीयता नीति',
    'terms_of_service' => 'सेवा की शर्तें',
    'processed_in' => 'संसाधित',
    'config_loader' => 'कॉन्फ़िगरेशन लोडर',
    'data_loader' => 'डेटा लोडर',
    'page_render' => 'पेज रेंडर',
    'copyright' => 'कॉपीराइट',
];
