<?php
 
return [
    'Login' => '登录',
    'Email Address' => '电子邮件 ID',
    'E-Mail Address' => '电子邮件地址',
    'Password' => '密码',
    'Confirm Password' => '确认密码',
    'Remember Me' => '记住我',
    'Forgot Your Password?' => '忘记密码？',
    'Register' => '注册',
    'Name' => '姓名',
    'Verify Your Email Address' => '验证您的电子邮件地址',
    'A fresh verification link has been sent to your email address.' => '新的验证链接已发送到您的电子邮件地址。',
    'welcome_back' => '欢迎回来！请登录以继续',
    'dont_have_account' => '还没有账号？',
    'register_here' => '点击此处注册',
    'already_have_account' => '已经有账号了？',
    'login_here' => '点击此处登录',
    'enter_password' => '输入您的密码',
    'your_email' => 'your@email.com',
    'your_full_name' => '您的全名',
    'choose_password' => '选择一个强密码',
    'confirm_password' => '确认您的密码',
    'one_last_step' => '保护您账户的最后一步',
    'before_proceeding' => '在继续之前，请检查您的电子邮件以获取验证链接。',
    'if_not_received' => '如果您没有收到电子邮件',
    'request_another' => '点击此处请求另一个',
    'create_new_password' => '为您的账户创建新密码',
    'enter_new_password' => '输入新密码',
    'confirm_new_password' => '确认新密码',
    'remember_password' => '记得您的密码吗？',
    'enter_email_reset' => '输入您的电子邮件以接收重置链接',
];
