<?php
 
return [
    'links' => '链接',
    'dashboard' => '管理',
    'profile' => '个人资料',
    'logout' => '登出',
    'login' => '登录',
    'register' => '注册',
    'support' => '支持',
    'contact_us' => '联系我们',
    'tnc' => '条款和条件',
    'follow_us' => '关注我们',
    'select_language' => '选择语言',
    'resources' => '资源',
    'get_in_touch' => '取得联系',
    'documentation' => '文档',
    'components' => '组件',
    'theme_setup' => '主题设置',
    'connect' => '连接',
    'all_rights_reserved' => '版权所有',
    'powered_by' => '技术支持',
    'privacy_policy' => '隐私政策',
    'terms_of_service' => '服务条款',
    'processed_in' => '处理于',
    'config_loader' => '配置加载器',
    'data_loader' => '数据加载器',
    'page_render' => '页面渲染',
    'copyright' => '版权',
];
